spring:
  config:
    activate:
      on-profile: dev

  devtools:
    add-properties: true

  datasource:
    url: jdbc:mysql://localhost:3306/fullStep
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: false

  sendgrid:
    apiKey: ${SENDGRID_API_KEY}
    fromEmail: hoangdinhdung0205@gmail.com
    templateId: d-31cf50168d7f4b95ba9122585e73941d
    verificationLink: http://localhost:8080/user/confirm-email

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: backend-service
    server: http://localhost:${server.port}
    title: Backend service
    version: 1.0.0

jwt:
  secretKey: abc@123